name: Basit CI Kontrolü

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Node.js yükle
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Basit sentaks kontrolü
        run: |
          # Buraya basit bir kontrol komutu ekleyebilirsin
          # Örneğin tüm js dosyalarını syntax kontrolü:
          find . -name "*.js" -exec node --check {} \;
